language: node_js
node_js:
- 10

sudo: required

script:
  - echo "hello"
branches:
  only:
  - deployment
before_install:
  - openssl aes-256-cbc -K $encrypted_e1982a93ff2e_key -iv $encrypted_e1982a93ff2e_iv
  -in jsdaddy_id_rsa.pem.enc -out ./jsdaddy_id_rsa.pem -d